### ISSUE TITLE
Assembly NASM Highlight Wrong

### ISSUE THREAD

**Issue by GabrielFrigo4** [naclsn/tree-sitter-nasm#3]
### Summary

![image](https://github.com/user-attachments/assets/d4be7a91-f296-46e8-91c8-e68ca9b53f35)

![image](https://github.com/user-attachments/assets/73301c82-8195-42bf-9b53-3e4e7b9e1e51)

It's easy to notice the error, it shouldn't have these characters colored white when there is a comment on the previous line

### Reproduction Steps

 

I tried this:

1. `hx assembly.asm` and type
```asm
; I expected this to happen:

word

; Instead, this happened:
word
```

I expected this to happen:
![image](https://github.com/user-attachments/assets/ce2d57a7-1499-49a2-a1bd-5be73dc09ab1)

Instead, this happened:
![image](https://github.com/user-attachments/assets/171d44a0-cd45-4ce8-ba56-5619aca1f650)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Windows

### Terminal Emulator

Windows Terminal

### Installation Method

winget

### Helix Version

helix 24.7 (079f5442)

# About this Issue

This is a bug that occurs in Helix, but Helix uses Tree-Sitter for syntax, which means the bug is probably in Tree-Sitter and the Helix moderators asked me to post the bug here. Also, SIMD/AVX registers are missing in Helix.

**Comment by naclsn** [comment]
I am not able to reproduce the issue, neither with helix nor with the tree-sitter CLI...
This is with a fresh build `helix 24.7 (079f5442`, but I also tried with latest `(5717aa8e)`:
![Screenshot_20240921_174954](https://github.com/user-attachments/assets/dc0a6804-db7f-47b0-ad16-02d839014050)

(and the `tree-sitter parse` output for completeness)
```c
(source_file [0, 0] - [6, 0]
  (comment [0, 0] - [0, 28])
  (source_line [2, 0] - [2, 4]
    (instruction [2, 0] - [2, 4]
      (actual_instruction [2, 0] - [2, 4]
        instruction: (word [2, 0] - [2, 4]))))
  (comment [4, 0] - [4, 25])
  (source_line [5, 0] - [5, 4]
    (instruction [5, 0] - [5, 4]
      (actual_instruction [5, 0] - [5, 4]
        instruction: (word [5, 0] - [5, 4])))))
```

Note that I am not doubting your word, this tree-sitter grammar is particularly capricious and inconsistent (as I was reminded in the minute after using it again); but even then these inconsistencies tend not to be in the middle of a word.

Can you still reproduce this weird highlighting on the last version of helix? What about with no config at all?

**Comment by GabrielFrigo4** [comment]
> I am not able to reproduce the issue, neither with helix nor with the tree-sitter CLI... This is with a fresh build `helix 24.7 (079f5442`, but I also tried with latest `(5717aa8e)`: ![Screenshot_20240921_174954](https://private-user-images.githubusercontent.com/43825779/369632186-dc0a6804-db7f-47b0-ad16-02d839014050.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NTIzNDUsIm5iZiI6MTcyNjk1MjA0NSwicGF0aCI6Ii80MzgyNTc3OS8zNjk2MzIxODYtZGMwYTY4MDQtZGI3Zi00N2IwLWFkMTYtMDJkODM5MDE0MDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDIwNTQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5N2U4YjFiZTJmMmVjZDY0NWU2NmJkNGRiOWYyODc3NWQ3OTYyMmNmNTQ1YWFkZDUxOTM5MGExNWJhYzYwYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HDS8gaceJpSl5-cIjnHyJSd35yjqpj0wMqYOQ9PbdcI)
> 
> (and the `tree-sitter parse` output for completeness)
> 
> ```c
> (source_file [0, 0] - [6, 0]
>   (comment [0, 0] - [0, 28])
>   (source_line [2, 0] - [2, 4]
>     (instruction [2, 0] - [2, 4]
>       (actual_instruction [2, 0] - [2, 4]
>         instruction: (word [2, 0] - [2, 4]))))
>   (comment [4, 0] - [4, 25])
>   (source_line [5, 0] - [5, 4]
>     (instruction [5, 0] - [5, 4]
>       (actual_instruction [5, 0] - [5, 4]
>         instruction: (word [5, 0] - [5, 4])))))
> ```
> 
> Note that I am not doubting your word, this tree-sitter grammar is particularly capricious and inconsistent (as I was reminded in the minute after using it again); but even then these inconsistencies tend not to be in the middle of a word.
> 
> Can you still reproduce this weird highlighting on the last version of helix? What about with no config at all?

This error only happens on Windows

On Windows I'm with `helix 24.7 (079f5442)` and has this error
On Manjaro (Notebook) and Arch (in WSL2) both in `helix 24.7`, they work correctly

**Comment by naclsn** [comment]
If the bug is platform dependent, I'm afraid this is not in my reach.
The code in this repository is a short JS file, that dictates how to generate a few C files, which in turn are compiled into a dynamic library.
I have no control over any of these steps, and none of them explicitly show platform-specific behavior or adaptations (past a few `#pragma warning` it seems).

If you think the problem really is with the compiled tree-sitter library, then I have no clue which link in the chain can cause this;
- the tree-sitter JS library?
- the JS to C generation?
- the resulting C?
- the compiler that was used on for your platform? (_could_ be, but I don't believe it)

Otherwise it's between helix and the terminal. It also seems unlikely to me, but support for ANSI escape sequences can be irregular from one terminal to the next.
What terminal emulator are you using? Can you try with an other one?

I don't have a Windows machine at disposition (I never got helix to work on one too), and I don't have the time to dig into helix's rendering. This is an annoying bug :/

---

Also I initially completely missed your mention of SIMD/AVX registers. These have been added to this repo a while ago, but it seem helix is still on an old commit from 2 years ago (a0db15d, [here](https://github.com/helix-editor/helix/blob/master/languages.toml#L2956)). It can certainly be updated with a PR over there (I can try to get to it in the week unless you beat me to it).

**Comment by naclsn** [comment]
If you can, clone this repo on your Windows installation and run the `tree-sitter parse assembly.asm` with the same file as your first post (after running `npm install` and what not of course). You hopefully should get the same output as I did.

**Comment by GabrielFrigo4** [comment]
> If the bug is platform dependent, I'm afraid this is not in my reach. The code in this repository is a short JS file, that dictates how to generate a few C files, which in turn are compiled into a dynamic library. I have no control over any of these steps, and none of them explicitly show platform-specific behavior or adaptations (past a few `#pragma warning` it seems).
> 
> If you think the problem really is with the compiled tree-sitter library, then I have no clue which link in the chain can cause this;
> 
> * the tree-sitter JS library?
> * the JS to C generation?
> * the resulting C?
> * the compiler that was used on for your platform? (_could_ be, but I don't believe it)
> 
> Otherwise it's between helix and the terminal. It also seems unlikely to me, but support for ANSI escape sequences can be irregular from one terminal to the next. What terminal emulator are you using? Can you try with an other one?
> 
> I don't have a Windows machine at disposition (I never got helix to work on one too), and I don't have the time to dig into helix's rendering. This is an annoying bug :/
> 
> Also I initially completely missed your mention of SIMD/AVX registers. These have been added to this repo a while ago, but it seem helix is still on an old commit from 2 years ago ([a0db15d](https://github.com/naclsn/tree-sitter-nasm/commit/a0db15db6fcfb1bf2cc8702500e55e558825c48b), [here](https://github.com/helix-editor/helix/blob/master/languages.toml#L2956)). It can certainly be updated with a PR over there (I can try to get to it in the week unless you beat me to it).

It would not be the terminal error, because I ran it on `Windows Terminal` and it gave an error, but I also ran it on `Windows Terminal` using `WSL2` with Arch-Linux and it worked.
In addition, the error also appears in `conhost`, the old version of the Windows terminal (resembles an `MS-DOS` console).

Since` AVX/SIMD` has been around for years in `tree-sitter-nasm`, I think this bug must have already been fixed in past versions of `tree-sitter-nasm` :)

And just to confirm, I've never compiled a `tree-sitter-xxx`
How do you do that?

**Comment by naclsn** [comment]
Sorry for the delay. I don't know if you've managed to try it in the mean time, but it should be fairly strait forward if you can have nodejs and npm.

I'm guessing along the line of:
```console
..> git clone https://github.com/naclsn/tree-sitter-nasm
..> cd tree-sitter-nasm
..> npm i
```

This hopefully should have fetched you the tree-sitter CLI, so (idk if you might have to use `.exe` or `.bat` or such):
```console
..> .\node_modules\bin\tree-sitter parse assembly.asm
```

**Comment by naclsn** [comment]
(https://github.com/helix-editor/helix/pull/11795 - note to self)
